# Generated by Django 4.2.4 on 2024-03-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_adminactount_user'),
        ('al_content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='cv',
            name='google_docs_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.adminactount'),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.adminactount'),
        ),
    ]
