# Generated by Django 4.2.4 on 2024-03-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('al_content', '0003_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='google_docs_link',
            new_name='my_cv',
        ),
    ]
