# Generated by Django 4.2.4 on 2024-03-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_content', '0004_rename_google_docs_link_cv_my_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='al_content/media/'),
        ),
    ]
