# Generated by Django 4.2.4 on 2024-03-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('al_content', '0005_alter_projects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
